name: test-upload

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir testdir && touch testdir/hello 
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: testdir/


      - run: rm -rf testdir

      - uses: actions/download-artifact@v3
    
      - run: ls -l
